#!/bin/sh

#References: 
#https://gist.github.com/alobato/1968852
#https://man7.org/linux/man-pages/man8/start-stop-daemon.8.html
#https://www.youtube.com/watch?v=ukQIf7i2UR4

NAME=aesdsocket

case "$1" in

    start)
        echo -n "Starting the daemon: "$NAME
        start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
        ;;

    stop)
        echo "Stopping the daemon: "$NAME
        start-stop-daemon -K -n aesdsocket
        ;;

    *)
        echo "Usage: $0 {start|stop}"
    exit 1

esac

exit 0
